title: Turtle race
hero_image: images/banner.png
description: Use random to race two turtles. The first one to reach the finish line wins.
version: 1
listed: true
copyedit: false
last_tested: "2025-01-01"
landing: true
steps:
  - title: Add a turtle
  - title: Add another turtle
    completion:
      - engaged
  - title: Add a third turtle
  - title: Add the fourth turtle
  - title: Get the track pen ready
  - title: Number the track
    completion:
      - internal
  - title: Draw the race markers
  - title: Start the race
    completion:
      - external
