title: Turtle race
hero_image: images/banner.png
description: Use random to race two turtles. The first one to reach the finish line wins.
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
landing: true
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8
    completion:
      - internal
      - external

